### ISSUE TITLE
App de Clima

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#10]
![IMG_20240130_171423.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/76540a8f-65e7-4d5a-95fd-e635051d62ed)

O app de Clima sempre mostra "Neblina" ao invés de Nublado.

![IMG_20240130_171437.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/02cfda9a-4427-4acf-a5a7-4395c5bb9112)

![IMG_20240130_171638.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/09ef17df-4829-4940-b6ef-ff4680d34ab2)

Não acredito ser um erro de previsão, pois no site do AccuWeather e na previsão do Google está "Nublado"

**Comment by DiorgenesS** [comment]
veja como a tradução se apresenta em Inglês por favor

**Comment by EduardoRGCM** [comment]
> veja como a tradução se apresenta em Inglês por favor

![Screenshot_2024-01-30-17-29-09-525_com.miui.weather2.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/bf96c07b-20b5-4fd7-bb25-df513827ed04)

**Comment by DiorgenesS** [comment]
https://www.earth.com/earthpedia-articles/haze/

A tradução está correta

**Comment by EduardoRGCM** [comment]
Sim, está correta no inglês e no português também.
Deve ser o aplicativo de Clima mesmo que tá errado, porque em todos os outros servidores de previsão do tempo aparece nublado, só no aplicativo da Xiaomi aparece "Neblina", e isso também no aplicativo da versão global.

**Comment by DiorgenesS** [comment]
Como a tradução está correta, vou fechar o problema.
