### ISSUE TITLE
Ligação Recebida

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#11]
![IMG_20240130_171805.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/a41a8832-ee34-41dc-a401-e103ec3063e6)

Ao receber uma ligação, na barra de status a informação está sem tradução

**Comment by DiorgenesS** [comment]
https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/commit/b66157f71ef8b0d2c84d62bab7a72d8ab0a42ad2
