### ISSUE TITLE
Bug ao conectar os Redmi Buds 4 Activate

### ISSUE THREAD

**Issue by AndreOliveiraBR02** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#13]
Há um bug no HyperOS da xiaomi eu, ao conectar o Redmi Buds 4 Ative a rede de internet ele não funciona mas, a não ser que você desativa o Bluetooth.

Dispositivo: Tapas

**Comment by DiorgenesS** [comment]
O problemas aqui são relacionados a tradução, o que acho improvável que seja esse caso.
Reporte em xiaomi.eu

**Comment by AndreOliveiraBR02** [comment]
Desculpa, e que eu nO consigo contactar wles
