### ISSUE TITLE
Proteção de carregamento 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#15]
![IMG_20240217_182156.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/1865c9e3-7c96-49be-8622-4a2593fe60f9)

Proteção de carregamento não está traduzido.

No local onde mostra a quantidade de cargas, falta um espaço entre o número e a palavra (2vezes).

**Comment by DiorgenesS** [comment]
Sobre o espaço, ocorre o mesmo no idioma ingles
