### ISSUE TITLE
Sensação térmica na tela de bloqueio 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#16]
![IMG_20240229_124339.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/07c83e7c-d2bc-4408-8e56-a263301e6de6)

**Comment by EduardoRGCM** [comment]
Na tela de edição, a tradução está ok, mas na tela de bloqueio não. ![Screenshot_2024-02-29-12-45-00-323_com.miui.aod.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/bdbb05a1-2a57-4373-a216-6bbde50d2029)

**Comment by DiorgenesS** [comment]
fiz uma pequena alteração na tradução
