### ISSUE TITLE
Galeria / Backup e restauração 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#18]
![IMG_20240329_004856.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/a5f4136a-f0fb-4be8-b932-fc420b604134)

![IMG_20240329_004922.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/84844c5e-ffaf-4c42-a912-d4d68260c05f)

![IMG_20240329_005126.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/eac322d4-fe9f-4deb-8767-e06dfaff9af6)

![IMG_20240329_010508.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/aead3bff-77d7-4766-975c-6419f658be5a)

Inclusive, onde está escrito "Vizualizar" o coreto seria "Visualizar"

**Comment by DiorgenesS** [comment]
Corrigido
