### ISSUE TITLE
Configurações da Tela inicial (não traduzido)

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#2]
![Screenshot_2024-01-05-00-46-15-848_com.miui.home-edit.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/e49c8af6-fa81-4168-9212-9ad8232093de)

**Comment by DiorgenesS** [comment]
https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/commit/1682c791cd8d6e58a11a1dd6d086f8ba462005eb
