### ISSUE TITLE
Configurações Adicionais de Alarme

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#20]
![IMG_20240418_002122.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/3d085efe-9d31-4214-af10-cb200ada920a)

**Comment by DiorgenesS** [comment]
https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/commit/75ac26e2d7152e026d58e1f14bb8ae634d8aa96a
