### ISSUE TITLE
Verificar atualização da Câmera 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#22]
![IMG_20240427_080448.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/d96b3b11-938e-4bab-989e-761b23239048)

**Comment by DiorgenesS** [comment]
Acredito que deve ser removido na próxima versão, pelo motivo de não ser possível atualizar apps dos sistemas, e no meu não aparece tais linhas e uso a versão semanal atualizada.

![WhatsApp Image 2024-05-01 at 10 33 32](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/71a5c1b7-968c-4571-b798-8000d041418c)

**Comment by EduardoRGCM** [comment]
Essa opção está presente na versão 5.2 do aplicativo de câmera, e parece que não foram todos os dispositivos que receberam essa versão, no Note 12 Pro 5g por exemplo não tinha, mas no Poco X6 Pro tem.

**Comment by DiorgenesS** [comment]
Envia o aplicativo

**Comment by EduardoRGCM** [comment]
https://drive.google.com/file/d/1qEYxh2KdQEfCNGiJX7k35H85RbLWrYDW/view?usp=sharing
