### ISSUE TITLE
Ajustes do Game Turbo 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#24]
![IMG_20240427_163035.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/27448bef-59ee-4d1f-aab5-fcd237f0806c)

![Screenshot_2024-04-27-16-29-35-483_io.github.lime3ds.android.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/454f3b6d-1f5d-4932-852f-5ebce2232a6b)

**Comment by DiorgenesS** [comment]
Eu fiz algumas traduções, vamos esperar pela próxima atualização, algumas delas já estavam traduzidas, então recomendo limpar os dados do app Segurança. Em relação ao caractere em Chinês eu não encontrei e no meu não aparace.
![WhatsApp Image 2024-05-01 at 10 28 59](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/81480dbb-af17-45a7-9c04-fdc46dab54fd)

**Comment by EduardoRGCM** [comment]
Recebi uma atualização hoje, e está tudo traduzido.
