### ISSUE TITLE
Pedido de tradução

### ISSUE THREAD

**Issue by kleidione** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#25]

**Comment by kleidione** [comment]
![Screenshot_2024-04-27-20-03-49-963_com android phone](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/48599586/59d758a0-9d0a-4244-9f22-d6c5a8fa7eb7)

**Comment by DiorgenesS** [comment]
Já está traduzido, tente limpar o cache (ou dados por sua conta em risco) do app com.androod.phone (Serviços do smartphone)
![image](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/eca95441-d825-45e1-891a-646defaa5053)
