### ISSUE TITLE
Informações sobre saúde da bateria 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#30]
Clicando em qualquer uma dessas seções (Saúde da Bateria, Temperatura ou Carregamentos Hoje) as informações aparecem em chinês.

Extraí o apk em que aparece essas informações, caso seja necessário.

https://drive.google.com/file/d/1LVcDcW1AsT4t27fbJBN1z28eKeCNGVtz/view?usp=sharing

![Screenshot_2024-05-04-20-59-42-408_com.miui.securitycenter.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/c7580d15-2f27-468d-8fff-4ad450778617)

![Screenshot_2024-05-04-20-59-36-416_com.miui.securityadd.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/0ed3dd28-a3d5-4c8f-9271-57e8af2f5aa1)

**Comment by EduardoRGCM** [comment]
Mudando o idioma para Inglês, as informações aparecem em inglês.
![Screenshot_2024-05-04-21-01-56-711_com.miui.securityadd.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/eb55e525-9e0e-4b89-b775-bfc5056de1e4)

**Comment by DiorgenesS** [comment]
envia o aplicativo de segurança, pois nao encontrei no que enviou

**Comment by EduardoRGCM** [comment]
> envia o aplicativo de segurança, pois nao encontrei no que enviou

https://drive.google.com/file/d/1ob0pVhtZR8htEBSxT3lIxEgPg-xHLjQb/view?usp=sharing

**Comment by DiorgenesS** [comment]
Também não encontrei, talvez esse texto venha de um servidor

**Comment by EduardoRGCM** [comment]
Pode ser, porque quando eu Clico em algum item ali, aparece uma página carregando.
https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/d4f9b9e4-50b6-4f96-8bee-57a0fabb0124

**Comment by DiorgenesS** [comment]
Isso vem do servidor, no meu celular ao clicar nesses itens nada acontece

**Comment by DiorgenesS** [comment]
Como não há opção de traduzir, vou fechar
