### ISSUE TITLE
Opções de Carregamento

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#38]
![IMG_20240518_125858.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/a671b2c4-76e5-4a3e-a210-b52168b63b4f)

![Screenshot_2024-05-18-12-57-47-699_com.miui.securitycenter.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/76349464-16b8-457f-a976-18beaa8c79ba)

**Comment by DiorgenesS** [comment]
Aguardar pela próxima art
