### ISSUE TITLE
Opções de tela de bloqueio em chinês 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#4]
![Screenshot_2024-01-05-11-16-47-321_com.miui.aod.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/fbf4d3ab-aebc-43d0-bdd1-11017fce463b)

**Comment by DiorgenesS** [comment]
Se você verificar em ingles também acontece.
Fiz umas mudanças: https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/commit/edaba2ffdb8ad118cd6d52f770828576f266cd99, não sei se vai resolver

**Comment by DiorgenesS** [comment]
Olhei na versão global e também é assim.

**Comment by DiorgenesS** [comment]
Na versão 24.1.xx foi corrigido
