### ISSUE TITLE
Xiaomi Cloud

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#40]
![Screenshot_2024-05-18-14-46-54-863_com.miui.cloudservice.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/c87b5e87-d046-4d7d-aa0e-5c695bed8c40)

**Comment by DiorgenesS** [comment]
Essas linhas ja foram traduzidas não sei o motivo de não está traduzido pra vc.

https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/main/Brazilian-Portuguese/main/CloudService.apk/res/values-pt-rBR/strings.xml#L395C19-L395C41

https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/main/Brazilian-Portuguese/main/CloudService.apk/res/values-pt-rBR/strings.xml#L979

https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/main/Brazilian-Portuguese/main/CloudService.apk/res/values-pt-rBR/strings.xml#L497

https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/main/Brazilian-Portuguese/main/CloudService.apk/res/values-pt-rBR/strings.xml#L354

https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/main/Brazilian-Portuguese/main/CloudService.apk/res/values-pt-rBR/strings.xml#L355

https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/main/Brazilian-Portuguese/main/CloudService.apk/res/values-pt-rBR/strings.xml#L356

https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/main/Brazilian-Portuguese/main/CloudService.apk/res/values-pt-rBR/strings.xml#L587

https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/main/Brazilian-Portuguese/main/CloudService.apk/res/values-pt-rBR/strings.xml#L193

https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/main/Brazilian-Portuguese/main/CloudService.apk/res/values-pt-rBR/strings.xml#L535

https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/main/Brazilian-Portuguese/main/CloudService.apk/res/values-pt-rBR/strings.xml#L259

**Comment by EduardoRGCM** [comment]
Verifiquei aqui, realmente estão traduzidas, deve ter sido algum bug.
