### ISSUE TITLE
Notificação do Gravador de Tela

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#42]
![IMG_20240525_192458.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/5ac2fc98-7328-4711-ab29-d3fbc900af5f)

**Comment by DiorgenesS** [comment]
Acredito que seja um bug, pois não existe tal linhas apenas com esse nome em inglês.

![image](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/f2d4ab53-e06f-4506-90a7-080d8dda44aa)

**Comment by EduardoRGCM** [comment]
Creio que deve ser uma nova versão do app de gravação de tela, porque ficou assim após a última atualização. A versão do app na rom que estou usando é a 2.14.0.0.1, vou deixar o apk disponível pra caso precisar verificar.

[https://drive.google.com/file/d/1KpVFzU0mDPAfaw27FHR6cZNyWg8WYSGb/view?usp=sharing](url)
