### ISSUE TITLE
Data na Tela de Bloqueio 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#5]
![Screenshot_2024-01-06-09-21-29-169_com.miui.aod.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/c9e6f7a5-c9a8-4371-806e-e7fede6c21c8)

Não sei se é algo que possa ser consertado na tradução ou depende de modificações no aplicativo, mas o formato da data está em padrão internacional (Mês/Dia) e não no que usamos (Dia/Mês)

**Comment by DiorgenesS** [comment]
Aqui está normal, eu tinha feito a correção ontem mesmo.

![image](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/f43a717b-ee0d-4796-a28d-0db2c452c86f)

**Comment by EduardoRGCM** [comment]
Entendi, então foi feito a correção depois do release dessa build que estou usando.

**Comment by DiorgenesS** [comment]
Estou usando a versão que saiu hoje e entrou em vigor

**Comment by EduardoRGCM** [comment]
Vou precisar esperar liberar uma atualização para o meu device, obrigado.

**Comment by EduardoRGCM** [comment]
> Estou usando a versão que saiu hoje e entrou em vigor

Você pode confirmar pra mim se no AOD fica o mesmo formato? Eu conferi aqui, no editor da tela de bloqueio ele aparece o formato Mês/Dia, mas na tela de bloqueio fica Dia/Mês.
Porém no AOD ainda permanece Mês/Dia tanto na pré visualização como no AOD ativo.

**Comment by DiorgenesS** [comment]
Apenas na visualização da última imagem mostra no formato mês/dia.

Vou verificar se tem como corrigir (mas acho que não)

![Screenshot_2024-01-06-10-13-41-966_com miui aod](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/e518f378-55fa-49d5-84cb-e7dd1e9f8465)
![Screenshot_2024-01-06-10-14-08-928_com miui aod](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/f908093f-0e67-4caf-aef5-e5feebd6dc56)
![Screenshot_2024-01-06-10-14-17-136_com android thememanager](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/ae841045-4b55-47f0-9992-5b3a8f3503b1)

**Comment by EduardoRGCM** [comment]
https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/0825e7d3-6071-4513-bb72-5ad363d97e97

Consegui gravar aqui, na tela de bloqueio fica correto (6/1) mas no AOD, ainda mostra 1/6

**Comment by DiorgenesS** [comment]
Qual versão tá usando?
Essas alterações estraram em vigor na 24.1.2/3......

**Comment by DiorgenesS** [comment]
Corrigido
