### ISSUE TITLE
Ações de Abrir e Responder notificações (Comentários Na Tela)

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#57]
![IMG_20240707_110036.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/a1cd2c65-73fb-4c55-ba44-9630b2ac1e1e)

![IMG_20240707_110056.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/e47b5316-520f-4475-81a4-196aea78e073)

Recentemente foi implementado a função "Comentários na tela" no GameTurbo. Quando você está com um jogo aberto, as notificações aparecem como texto rolando na tela e se você clicar no texto, aparece a opção de abrir ou responder (varia de acordo com o app) e ainda não estão traduzidas.

**Comment by igormiguell** [comment]
corrigido
