### ISSUE TITLE
Barra Lateral

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#59]
![Screenshot_2024-07-13-22-25-41-984_com.miui.securitycenter.jpg](https://github.com/user-attachments/assets/752bbf57-0ac0-405f-87d6-26ea94996b0f)

![IMG_20240713_223739.jpg](https://github.com/user-attachments/assets/9206f4e7-5d15-42b1-882d-48f5bff1c3e1)

![IMG_20240713_223728.jpg](https://github.com/user-attachments/assets/9a6ab499-7d36-4ee4-8a77-944f6eb862c9)

As novas opções da barra lateral estão sem tradução

**Comment by igormiguell** [comment]
já estão todas traduzidas
