### ISSUE TITLE
Remover atalho da tela inicial

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#6]
![Screenshot_2024-01-11-08-41-41-277_com.miui.home.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/f30ffc31-4982-4022-a647-09b93a0439a6)

Não sei se pode ser a falta de tradução ou é pra ser assim mesmo, mas deveria ser "Remover" ao invés de "Remove".

**Comment by DiorgenesS** [comment]
Aqui está traduzid.

![Screenshot_2024-01-11-11-02-12-821_com miui home](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/efbf67ce-29c1-4b97-bcc7-d61c41f3b744)
![Screenshot_2024-01-11-11-02-17-944_com miui home](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/408de628-19a9-4b08-872f-97e1e27c1eaa)

**Comment by EduardoRGCM** [comment]
Tente em algum atalho do sistema, como do GameBooster por exemplo.

**Comment by DiorgenesS** [comment]
Corrigido -> https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/commit/e0b40c2ba60f9ab07b4a694561f44a16458fb150#diff-f0336a79269ed8211d1a79c93f60cf9276d4224bf808b4bddee19d5ecbf7b01fR994
