### ISSUE TITLE
Comentários na Tela: Sugestão

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#60]
![IMG_20240714_000014.jpg](https://github.com/user-attachments/assets/0ae730a9-eb55-49b9-b022-08664c43201b)

![IMG_20240714_000033.jpg](https://github.com/user-attachments/assets/6f993362-00b5-4833-a133-48474f36b61a)

Como não aparece a palavra "Responder" completa, tanto em retrato como em paisagem, não poderia ficar abreviado como "Resp."?

**Comment by igormiguell** [comment]
corrigido
