### ISSUE TITLE
Arquivos Recebidos por Bluetooth

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#61]
![IMG_20240714_135851.jpg](https://github.com/user-attachments/assets/a29b5d22-d12a-4f8a-9a28-3a4babbb4066)

**Comment by igormiguell** [comment]
fiz uma alteração, vamos ver se resolve.

**Comment by EduardoRGCM** [comment]
![Screenshot_2024-07-22-21-50-50-375_com.android.systemui.jpg](https://github.com/user-attachments/assets/aa397315-9ffd-4b3e-a805-bc22aa4995ec)

Ainda continua sem tradução

**Comment by DiorgenesS** [comment]
![Screenshot_2024-07-22-23-39-46-552_com android settings](https://github.com/user-attachments/assets/ce74cbb7-74ca-45cc-9fa7-17e9b88b8951)
Aqui está traduzido
