### ISSUE TITLE
Compartilhamento Mi

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#62]
O compartilhamento Mi foi renomeado de Mi Share para Xiaomi Share, em inglês o nome está correto mais em PT-BR ainda está com o nome antigo.

![Screenshot_2024-07-16-17-16-47-963_com.miui.mishare.connectivity.jpg](https://github.com/user-attachments/assets/ac5deb95-8f1c-4299-8a3d-1d7ffb52dfb1)
EN-US

![Screenshot_2024-07-16-17-17-19-850_com.miui.mishare.connectivity.jpg](https://github.com/user-attachments/assets/04d44be3-c292-4077-a82f-06ee8b03c76b)

PT-BR

**Comment by igormiguell** [comment]
essa parte ja esta traduzida

**Comment by EduardoRGCM** [comment]
![IMG_20240716_213707_653.jpg](https://github.com/user-attachments/assets/25df2b4a-8f6d-4414-9f18-01e5f0a623ab)

Consegui um print de como é na versão global, só pra referência.

**Comment by igormiguell** [comment]
obrigado pelo print, irei fazer alguns ajustes
