### ISSUE TITLE
Modo Desempenho Game Turbo

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#64]
Gostaria de sugerir que fosse alterado a tradução de "Modo Balanceado" Para "Balanceado" e "Modo Desempenho" para "Wild Boost", ficando em conformidade com a versão Global em PT-BR e a versão em EN.

![IMG_20240804_125628.jpg](https://github.com/user-attachments/assets/3e53f457-c71b-4cc4-b72d-8708eee8bff3)

Segue captura de tela da versão Global para referência:

![photo_2024-08-04_17-43-00](https://github.com/user-attachments/assets/9073ff33-db72-468e-97fa-ab3b8eb54d8c)

[#L2221](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/blob/78e5b250a72846af244e11234ddf91c2223db25f/Brazilian-Portuguese/main/SecurityCenter.apk/res/values-pt-rBR/strings.xml#L2221)

**Comment by igormiguell** [comment]
@DiorgenesS o que você acha?

**Comment by DiorgenesS** [comment]
> @DiorgenesS o que você acha?

Talvez na versão global ainda não tenha sido traduzido, na minha opinião para esse caso eu deixaria traduzido

**Comment by EduardoRGCM** [comment]
> > @DiorgenesS o que você acha?
> 
> Talvez na versão global ainda não tenha sido traduzido, na minha opinião para esse caso eu deixaria traduzido

Eu mencionei essa linha em específico porque realmente para alguns dispositivos (Linha K70 e Poco F6 Pro) é realmente Wild Boost, e pra outros demais é Modo Performance.
Porém, no meu caso que é o K70E, de toda forma está como Modo Performance.

**Comment by EduardoRGCM** [comment]
Tradução oficial da versão global mais recente:

    <string name="game_performance_wild_mode">Wild Boost</string>
    <string name="game_performance_wild_mode_tips">"Ative para melhorar o desempenho do dispositivo
(O seu dispositivo superaquecerá e consumirá mais energia)"</string>

**Comment by IgorEisberg** [comment]
The term "Wild Boost" is not translatable just like "Google" or "Xiaomi" are not translatable. It's simply a trademark.
Also, "Wild Boost" is a special mode that replaces "Performance" for a few specific devices, like Eduardo mentioned.
Will be filtered out of translations starting from next build.
