### ISSUE TITLE
Super Wallpaper/ Lua

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#66]
![Screenshot_2024-08-13-09-02-45-518_com.android.thememanager.jpg](https://github.com/user-attachments/assets/4e891854-cfcf-491a-8806-6a18e10953f6)

Não tenho certeza se essa tradução é feita pelo time de tradução ou pela Xiaomi, mas não está traduzido.

**Comment by igormiguell** [comment]
Onde você encontrou isso? Tentei procurar aqui e sem sucesso. Creio que seja feito pela Xiaomi.

**Comment by EduardoRGCM** [comment]
Ficam em Configurações> Personalização> Wallpaper> Super Planos de Fundo.

Mas eu verifiquei, realmente não há como fazer a tradução.
