### ISSUE TITLE
Widget de calendário 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#68]
![IMG_20240827_181219.jpg](https://github.com/user-attachments/assets/8abde3f5-8a67-4e4d-be42-323e619aa912)

**Comment by igormiguell** [comment]
Tentei encontrar essas strings, mas não consegui, nem a do E-mail onde está escrito Mail.
@DiorgenesS você conseguiu encontrar?

**Comment by EduardoRGCM** [comment]
> Tentei encontrar essas strings, mas não consegui, nem a do E-mail onde está escrito Mail.
> @DiorgenesS você conseguiu encontrar?

    <string name="agenda_view">Events</string>
    <string name="gadget_title">Calendar</string>

Está no app de calendário

**Comment by igormiguell** [comment]
Já está traduzido

**Comment by EduardoRGCM** [comment]
![Screenshot_2024-09-28-21-44-18-232_com.miui.home.jpg](https://github.com/user-attachments/assets/12e2bd7f-d5f4-4de0-8af7-533023bf3d70)

Vou fechar o issue porque já foi corrigido
