### ISSUE TITLE
Compartilhamento de Áudio via Bluetooth 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#69]
Ao usar a função de compartilhar áudio em mais de um dispositivo Bluetooth, a notificação não está traduzida.

![Screenshot_2024-09-22-13-27-48-662_tw.nekomimi.nekogram.jpg](https://github.com/user-attachments/assets/bc6c9f12-d2d2-4ba8-9cb5-5cbc26cac653)

**Comment by EduardoRGCM** [comment]
Bluetooth.apk/res/values/strings.xml:    <string name="bt_audio_share_notification_title">Sharing audio</string>
MiConnectService.apk/res/values/strings.xml:    <string name="bt_audio_share_notification_title">Sharing audio</string>

**Comment by EduardoRGCM** [comment]
```
Bluetooth.apk/res/values/strings.xml:    <string name="bt_audio_share_notification_title">Sharing audio</string>
MiConnectService.apk/res/values/strings.xml:    <string name="bt_audio_share_notification_title">Sharing audio</string>
```

**Comment by igormiguell** [comment]
Verifiquei aqui e essas linhas já estão traduzidas. Se na próxima atualização não estiverem traduzidas, você pode reabrir o problema.
