### ISSUE TITLE
Compartilhar aplicativo 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#7]
![IMG_20240111_133312.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/d7fcc2f5-4c32-424f-8162-9d368bf5b4db)

**Comment by DiorgenesS** [comment]
![Screenshot_2024-01-11-15-10-01-162_com miui securitycenter](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/a59aac33-a4c6-405b-ae9a-6a7e589f2dd2)
