### ISSUE TITLE
Aplicativo de calendário

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#71]
O aplicativo de calendário foi atualizado, e agora será usado a versão base chinesa e ainda faltam algumas traduções.

Esse aplicativo ainda é o mesmo tanto pra HyperOS 1.0 e HyperOS 2, vou deixar o link do apk atualizado abaixo.

https://drive.google.com/file/d/1M1_hf7YQ0o5V-q4BhdIsfAYmCG8OHNb9/view?usp=drivesdk

![IMG_20241108_090259.jpg](https://github.com/user-attachments/assets/6e9e25b6-d75b-4aa5-973e-13f0a5c99ec5)

![IMG_20241108_090246.jpg](https://github.com/user-attachments/assets/de70831e-5038-4e75-bc29-19751b7c31df)

![IMG_20241108_090319.jpg](https://github.com/user-attachments/assets/19d6d9ea-b1dc-43c7-be90-604f623fca2e)

![Screenshot_2024-11-09-10-36-09-988_com.android.calendar.jpg](https://github.com/user-attachments/assets/d2dece94-bb66-4886-83e0-c8e820226f7d)

![Screenshot_2024-11-09-10-36-18-612_com.android.calendar.jpg](https://github.com/user-attachments/assets/3ee78d3b-68f1-4842-9ffb-341b874dd8dd)

![Screenshot_2024-11-09-10-36-14-400_com.android.calendar.jpg](https://github.com/user-attachments/assets/289bc7dd-99d6-4e13-85be-0764acd9bbf7)

![IMG_20241109_103647.jpg](https://github.com/user-attachments/assets/3b4d38a6-e2c0-4860-a717-7b85d2f70d17)

Essa captura abaixo é no app vault:

![IMG_20241108_092634.jpg](https://github.com/user-attachments/assets/9c409175-98c8-42a4-a6e6-ac58ab66e189)

**Comment by igormiguell** [comment]
corrigido
