### ISSUE TITLE
Aplicativo Scanner/Digitalizador

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#72]
O aplicativo de Scanner (Antes Digitalizador) agora também será usado a versão chinesa, e alguns itens ainda estão sem a tradução.

Segue o link do apk atualizado:

https://drive.google.com/file/d/1MxWJMPdVUZnlSkY63WAHZOB39dRy7HD7/view?usp=drivesdk

![Screenshot_2024-11-10-12-15-31-058_com.xiaomi.scanner.jpg](https://github.com/user-attachments/assets/8cd2cc01-c776-414d-922c-1532196f8cd8)

![Screenshot_2024-11-10-12-18-44-874_com.xiaomi.scanner.jpg](https://github.com/user-attachments/assets/4a11f961-12f2-46d2-884b-307cdfbc6448)

![IMG_20241110_122005.jpg](https://github.com/user-attachments/assets/35100ae9-71f1-470d-9522-6c4e6bde5edb)

![IMG_20241110_121742.jpg](https://github.com/user-attachments/assets/d718cc1c-a378-4651-9224-cecfe4228e43)

![IMG_20241110_121924.jpg](https://github.com/user-attachments/assets/0df7364a-09e6-4348-84e9-2b708048f3bf)

![IMG_20241110_122027.jpg](https://github.com/user-attachments/assets/17a9080a-b9d4-445f-bc4d-1d042bb8ee17)

**Comment by igormiguell** [comment]
corrigido
