### ISSUE TITLE
MiuiHome / Circule para Pesquisar

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#73]
<string name="navigation_guide_circle_search_summary">Press and hold full screen indicator to use Circle to Search</string>
    <string name="navigation_guide_circle_search_title">Circle to Search</string>

A partir das próximas atualizações, essas linhas estarão presentes no launcher, tanto nas versões HyperOS 2 como também na versão HyperOS 1.0

![IMG_20241113_113948_734.jpg](https://github.com/user-attachments/assets/36d0ab8c-a480-4a5b-ae17-c7cad417a882)

**Comment by igormiguell** [comment]
corrigido
