### ISSUE TITLE
HyperOS 2

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#75]
A primeira build de testes do HyperOS foi disponibilizada pra o meu dispositivo, e aparentemente existem poucas coisas sem tradução, a maioria no aplicativo de Temas e Configuração. 
Vou deixar anexado os apks extraídos.
[OS2 Apks](https://drive.google.com/drive/folders/1R2d4imYE2RwChoDz-ZVzc4fILL4ZQFS_?usp=sharing)

![Screenshot_2024-11-15-20-04-31-492_com.android.incallui.jpg](https://github.com/user-attachments/assets/30960c83-cd85-400b-86b3-b3391c924f40)

![Screenshot_2024-11-15-20-43-20-667_com.android.thememanager.jpg](https://github.com/user-attachments/assets/0b3084a4-4087-4965-bc7f-bdf1c95d1c19)

![Screenshot_2024-11-15-20-20-11-702_com.android.thememanager.jpg](https://github.com/user-attachments/assets/936e63b4-4c08-4bed-bf7d-61bda5360a34)

![IMG_20241115_204952.jpg](https://github.com/user-attachments/assets/1f8dbf2b-c3d5-40b5-a587-c5244be45dc4)

![Screenshot_2024-11-15-20-43-37-725_com.android.settings.jpg](https://github.com/user-attachments/assets/93d426f2-b6c9-4433-83c2-e4630863dbd3)

![Screenshot_2024-11-15-20-43-46-669_com.android.settings.jpg](https://github.com/user-attachments/assets/96f144d1-9514-4537-8033-1e045f964868)

![IMG_20241115_205016.jpg](https://github.com/user-attachments/assets/2ecd5965-fa3a-41be-81ec-2409ac93b18e)

![IMG_20241115_205216.jpg](https://github.com/user-attachments/assets/df97875f-3ec7-4040-8d3c-18c844f53358)

![IMG_20241115_205108.jpg](https://github.com/user-attachments/assets/9442c3e0-8a41-4031-a4cb-9de4d51a520c)

![IMG_20241115_205151.jpg](https://github.com/user-attachments/assets/41df4221-fd4a-4f92-b78f-723a7374e77c)

![IMG_20241115_204931.jpg](https://github.com/user-attachments/assets/2b8bd941-0820-4f0d-a6fe-6fc16680650c)

**Comment by igormiguell** [comment]
Jajá estarei corrigindo isso. Estou verificando XML por XML da HyperOS 2 em busca de novas traduções e para melhorar a consistência.

**Comment by EduardoRGCM** [comment]
Estou à disposição caso precise de algo
