### ISSUE TITLE
Desativar App nas configurações 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#8]
![IMG_20240114_122725.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/02fc3c2a-e640-41fc-b2a2-7f4f42abbacd)

**Comment by DiorgenesS** [comment]
Ja estava traduzido -> https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/commit/906b7f0b2e653e715c0ca9c45d79c964c8dd3e92#diff-ee25085ad5ba72325462ac1bad59cd265bc54c6e19af21eeb566d7a83061ee7aR161

**Comment by DiorgenesS** [comment]
![Screenshot_2024-01-14-19-31-34-295_com miui securitycenter](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/e7ec01ba-c63d-4e89-838d-905c53dfd388)
![Screenshot_2024-01-14-19-31-22-870_com miui securitycenter](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/b8cfebdb-d9c3-4b17-ae73-74684e2835ff)
