### ISSUE TITLE
Xiaomi Share

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#81]
Ao compartilhar itens com o Bluetooth ligado, notei esse bug na tradução 
![IMG_20241119_114718.jpg](https://github.com/user-attachments/assets/7e104d01-6ecc-419d-a0e7-accda33a6ab2)

**Comment by igormiguell** [comment]
Era um espaço a mais que tinha na tradução. Se não corrigir, me avise. Daqui a pouco, vou lançar um commit com essas correções.
