### ISSUE TITLE
Itens sem tradução

### ISSUE THREAD

**Issue by gabrielvmouro** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#85]
![Screenshot_2024-11-22-21-53-00-601_com android settings-edit](https://github.com/user-attachments/assets/ad93ffcb-9de8-4e3d-befb-c432050762ef)
![Screenshot_2024-11-22-21-53-31-823_com miui securitycenter-edit](https://github.com/user-attachments/assets/ca74c8b6-4dfd-4945-826c-f10a32cb32f4)
![Screenshot_2024-11-22-21-53-48-119_com android thememanager-edit](https://github.com/user-attachments/assets/62464e0b-f9fc-420f-8f17-53a411543e44)
![Screenshot_2024-11-22-21-54-01-903_com android thememanager-edit](https://github.com/user-attachments/assets/f36031a0-0c83-436e-a594-d7be33739c2e)
![Screenshot_2024-11-22-21-54-11-913_com android thememanager](https://github.com/user-attachments/assets/e73f8c57-d39e-4e18-a20e-77b867de709e)
![Screenshot_2024-11-22-21-54-18-599_com android thememanager](https://github.com/user-attachments/assets/b32e7b75-43f2-427b-b922-7bf95e3b8478)
![Screenshot_2024-11-22-21-54-22-491_com android thememanager](https://github.com/user-attachments/assets/f850f747-ffc2-4244-be41-ed3d06c2b929)
![Screenshot_2024-11-22-21-55-27-939_com android thememanager](https://github.com/user-attachments/assets/4bca6791-a605-4344-a070-eba9d93eb6c3)

**Comment by igormiguell** [comment]
corrigido
