### ISSUE TITLE
Chaves de acesso

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#86]
![photo_2024-11-22_22-27-37](https://github.com/user-attachments/assets/b383ef9d-c2b8-4b27-8a82-605756f7a0db)
 Encontrei a string em Xiaomi.eu-HyperOS-2.0-XML-Compare\aurora\MiuiCredentialManager.apk\res\values\strings.xml mas não achei a xml para fazer a tradução

**Comment by igormiguell** [comment]
Estou traduzindo isso, daqui um tempo eu termino.

**Comment by igormiguell** [comment]
corrigido
