### ISSUE TITLE
Proteção de Privacidade / Sem tradução 

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#9]
![Screenshot_2024-01-26-02-08-01-628_com.miui.securitycenter-edit.jpg](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/91606482/5f1b9a71-e3f7-4e24-ab28-2ec6e5be7f50)

**Comment by DiorgenesS** [comment]
Já está traduzido

![Screenshot_2024-01-26-07-06-37-500_com miui securitycenter](https://github.com/RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN/assets/16513009/7df31779-995c-46f1-8425-a8637b663b58)

**Comment by IgorEisberg** [comment]
Strings ending with "_behavior" are usually not translatable, but this one ("recent_app_behavior") is an exception, so I added it to the whitelist. Thanks.
