### ISSUE TITLE
Restringir atividades em segundo plano

### ISSUE THREAD

**Issue by EduardoRGCM** [RicardoGuariento/HyperOS-XML-1.0-BRAZILIAN#95]
![photo_2024-12-05_09-01-21](https://github.com/user-attachments/assets/f1c44198-7159-440f-95d9-5543bdadfa7e)

@igormiguell você poderia me contatar pelo [Telegram](https://t.me/eduardorgcm) ou me passar algum outro contato que eu possa falar com você sobre esse issue e algumas outras traduções?

**Comment by igormiguell** [comment]
desculpa pela demora, posso sim.
